### ISSUE TITLE
Add information regarding hostonlyif

### ISSUE THREAD

**Issue by purarue** [purarue/k_grok#1]
It is not possible to choose a network name for a Host-Interface Network (`hostonlyif`), and the script assumes `vboxnet1`, despite this not always being the defualt name after creation.

Add some comments to near [Host Configuration Phase](https://github.com/seanbreckenridge/k_grok/blob/master/config/virtualbox#L77) describing how to debug this.

**Comment by purarue** [comment]
Should probably include commands like `VBoxManage list hostonlyifs` and `VBoxManage hostonlyif remove "<networkname>"` and describing what these do

**Comment by thtrngo** [comment]
let me know if I should make any changes!

**Comment by purarue** [comment]
e8b1af52e609a6e8a2ed29b904035b4b5e37b423 Removed modify VM as it doesnt work for networks

**Comment by purarue** [comment]
19166e56a0f9fa1dd5612b2346d86ff8a07ccd82 use a variable to make managing host-interface networks easier

a884fe29833fbc36fd239e4ededda8a6e63d2d19 merge explanations

**Comment by purarue** [comment]
Note: This also changed VDI to match a wildcard, so it matches any Ubuntu 64-bit .vdi file
`export VDI="$VM_DISK_DIR/Ubuntu*(64bit).vdi"`

**Comment by purarue** [comment]
Note: The VDI Wildcard matching was removed: d7a8f6e8f07cffd774d7cd6b1bafec919010c8d1
